SET NOCOUNT ON;

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'MUONG', N'Mường', N'Muong',
       N'Dân tộc Mường có không gian văn hóa đặc sắc ở vùng trung du và miền núi Bắc Bộ, nổi bật với mo Mường, nhà sàn và lễ hội truyền thống.',
       N'The Muong people are known for distinctive culture in the northern midlands and mountains, especially Mo Muong rituals, stilt houses, and traditional festivals.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'MUONG');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'THAI', N'Thái', N'Thai',
       N'Dân tộc Thái sinh sống nhiều ở Tây Bắc, nổi bật với nghệ thuật xòe, nhà sàn và đời sống bản mường ven suối.',
       N'The Thai people live widely in the Northwest and are known for xoe dance, stilt houses, and village life by streams.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'THAI');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'BANA', N'Ba Na', N'Ba Na',
       N'Dân tộc Ba Na gắn với không gian nhà rông, lễ hội cộng đồng và đời sống văn hóa Tây Nguyên.',
       N'The Ba Na are associated with communal rong houses, festivals, and Central Highlands cultural life.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'BANA');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'JRAI', N'Jrai', N'Jrai',
       N'Dân tộc Jrai nổi bật với sử thi, nhà rông, cồng chiêng và đời sống cộng đồng ở Tây Nguyên.',
       N'The Jrai are known for epic traditions, rong houses, gong culture, and communal life in the Central Highlands.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'JRAI');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'NUNG', N'Nùng', N'Nung',
       N'Dân tộc Nùng có đời sống văn hóa gần gũi với vùng Đông Bắc, nổi bật với làn điệu dân ca, lễ hội và nghề thủ công.',
       N'The Nung are rooted in the Northeast and known for folk songs, festivals, and craft traditions.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'NUNG');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'HANI', N'Hà Nhì', N'Ha Nhi',
       N'Dân tộc Hà Nhì sinh sống tại vùng biên giới Tây Bắc, nổi bật với ruộng bậc thang, trang phục và tín ngưỡng cộng đồng.',
       N'The Ha Nhi live in the northwestern borderlands and are known for terraces, traditional dress, and communal beliefs.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'HANI');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'COTU', N'Cơ Tu', N'Co Tu',
       N'Dân tộc Cơ Tu gắn với văn hóa miền núi Trường Sơn, nổi bật với nhà Gươl, điêu khắc gỗ và lễ hội cộng đồng.',
       N'The Co Tu are associated with the Truong Son mountains and known for Guol houses, wood carving, and community rituals.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'COTU');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'TAOI', N'Tà Ôi', N'Ta Oi',
       N'Dân tộc Tà Ôi gắn với dệt zèng, lễ hội và đời sống cộng đồng ở dãy Trường Sơn.',
       N'The Ta Oi are known for zeng weaving, festivals, and community life along the Truong Son range.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'TAOI');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'CHURU', N'Chu Ru', N'Chu Ru',
       N'Dân tộc Chu Ru mang nhiều nét văn hóa giao thoa giữa Tây Nguyên và duyên hải Nam Trung Bộ.',
       N'The Chu Ru reflect cultural interactions between the Central Highlands and the south-central coast.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'CHURU');

INSERT INTO dbo.DanToc (MaDanToc, TenVI, TenEN, MoTaVI, MoTaEN, HoatDong)
SELECT 'SANDIU', N'Sán Dìu', N'San Diu',
       N'Dân tộc Sán Dìu nổi bật với dân ca Soọng cô, lễ tục cộng đồng và đời sống trung du Bắc Bộ.',
       N'The San Diu are known for Soong Co singing, communal rituals, and life in the northern midlands.',
       1
WHERE NOT EXISTS (SELECT 1 FROM dbo.DanToc WHERE MaDanToc = 'SANDIU');

MERGE dbo.DanTocProfile AS target
USING (
    SELECT dt.DanTocID, dt.MaDanToc,
        v.HeroBackgroundImageUrl, v.HeroBackgroundAltVI, v.HeroBackgroundAltEN,
        v.HeroForegroundImageUrl, v.HeroForegroundAltVI, v.HeroForegroundAltEN,
        v.IntroImageUrl, v.IntroImageAltVI, v.IntroImageAltEN,
        v.FeatureHighlightImageUrl, v.FeatureHighlightAltVI, v.FeatureHighlightAltEN,
        v.MusicImageUrl, v.MusicImageAltVI, v.MusicImageAltEN,
        v.ArchitectureImageUrl, v.ArchitectureImageAltVI, v.ArchitectureImageAltEN,
        v.CardImageUrl, v.CardImageAltVI, v.CardImageAltEN,
        v.HeroSubtitleVI, v.HeroSubtitleEN,
        v.OverviewTitleVI, v.OverviewTitleEN, v.OverviewBodyVI, v.OverviewBodyEN,
        v.HistoryTitleVI, v.HistoryTitleEN, v.HistoryBodyVI, v.HistoryBodyEN,
        v.CultureTitleVI, v.CultureTitleEN, v.CultureBodyVI, v.CultureBodyEN,
        v.ArchitectureTitleVI, v.ArchitectureTitleEN, v.ArchitectureBodyVI, v.ArchitectureBodyEN,
        v.PrimaryRegionLabelVI, v.PrimaryRegionLabelEN, v.PopulationLabelVI, v.PopulationLabelEN,
        v.DisplayOrder
    FROM dbo.DanToc dt
    JOIN (VALUES
        ('MUONG',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',N'Không gian miền núi gắn với người Mường',N'Mountain landscape associated with the Muong people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Mường',N'Muong portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Đời sống người Mường',N'Muong cultural life',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Không gian văn hóa người Mường',N'Muong cultural scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật của người Mường',N'Muong performance arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Nhà sàn của người Mường',N'Muong stilt house',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Mường',N'Muong card image',N'Dân tộc Mường gắn với không gian nhà sàn, mo Mường và đời sống cộng đồng vùng trung du, miền núi Bắc Bộ.',N'The Muong are associated with stilt houses, ritual chants, and community life in northern midland and mountain areas.',N'Giới thiệu về người Mường',N'Introduction to the Muong people',N'Người Mường sinh sống tập trung tại Hòa Bình, Thanh Hóa và các vùng lân cận, lưu giữ nhiều giá trị văn hóa phong phú qua mo Mường, lễ hội và sinh hoạt nhà sàn. Những nét ấy tạo nên một không gian văn hóa riêng của vùng trung du và miền núi Bắc Bộ.',N'The Muong live mainly in Hoa Binh, Thanh Hoa, and nearby areas, preserving rich cultural values through ritual chants, festivals, and stilt-house life.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Mường có lịch sử cư trú lâu đời ở vùng trung du, miền núi phía Bắc, gắn bó với ruộng bậc thấp, suối nguồn và các mối liên kết cộng đồng bản làng.',N'The Muong have a long history in the northern midlands and mountains, closely tied to low terraces, streams, and village solidarity.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Nhà sàn, mo Mường, lễ hội cầu mùa và kho tàng dân ca đã tạo nên dấu ấn văn hóa đặc sắc của người Mường qua nhiều thế hệ.',N'Stilt houses, ritual chants, seasonal festivals, and folk songs define Muong culture across generations.',N'Không gian sống',N'Living Space',N'Không gian sống của người Mường gắn với thung lũng, nương rẫy và nhà sàn quần tụ theo bản làng.',N'Muong living space is associated with valleys, upland fields, and clustered stilt-house villages.',N'Trung du và miền núi phía Bắc',N'Northern midlands and mountains',N'Hơn 1,4 triệu người',N'Over 1.4 million people',8),
        ('THAI',N'https://images.unsplash.com/photo-1605518215584-5ea1ebda40c0?auto=format&fit=crop&w=1600&q=80',N'Không gian Tây Bắc gắn với người Thái',N'Northwest landscape associated with the Thai people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Thái',N'Thai portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Thái',N'Thai community life',N'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật xòe Thái',N'Thai xoe dance scene',N'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật xòe và trình diễn của người Thái',N'Thai dance performance scene',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Nhà sàn người Thái',N'Thai stilt house',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Thái',N'Thai card image',N'Dân tộc Thái gắn với điệu xòe, nhà sàn và đời sống bản mường vùng Tây Bắc.',N'The Thai people are known for xoe dance, stilt houses, and village life in the Northwest.',N'Giới thiệu về người Thái',N'Introduction to the Thai people',N'Người Thái là một trong những cộng đồng đông dân ở Tây Bắc, nổi bật với nghệ thuật xòe, điệu khắp và cấu trúc bản mường ven suối. Không gian sống, lễ hội và trang phục đã tạo nên sắc thái văn hóa đậm đà của cộng đồng này.',N'The Thai are one of the major populations in the Northwest, known for xoe dance, khap singing, and stream-side village organization.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Thái có lịch sử lâu đời ở Tây Bắc, gắn với thung lũng, ruộng nước và mạng lưới bản mường đặc trưng.',N'The Thai have a long history in the Northwest, connected to valleys, rice fields, and traditional muong settlements.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Điệu xòe, khèn bè, khăn piêu và nếp sống nhà sàn là những yếu tố làm nên diện mạo văn hóa đặc sắc của người Thái.',N'Xoe dance, panpipes, embroidered scarves, and stilt-house life define Thai cultural identity.',N'Không gian sống',N'Living Space',N'Không gian sống của người Thái gắn với thung lũng, suối nguồn và các bản nhà sàn ven ruộng nước.',N'Thai living space is linked to valleys, streams, and stilt-house villages by rice fields.',N'Tây Bắc',N'Northwest',N'Hơn 1,8 triệu người',N'Over 1.8 million people',9),
        ('BANA',N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',N'Không gian Tây Nguyên gắn với người Ba Na',N'Central Highlands landscape associated with the Ba Na people',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Chân dung người Ba Na',N'Ba Na portrait',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Ba Na',N'Ba Na community life',N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',N'Không gian nhà rông của người Ba Na',N'Ba Na rong house scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng của người Ba Na',N'Ba Na communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Ba Na',N'Ba Na living space',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Ba Na',N'Ba Na card image',N'Dân tộc Ba Na nổi bật với nhà rông, cồng chiêng và lễ hội cộng đồng của Tây Nguyên.',N'The Ba Na are known for rong houses, gong culture, and communal festivals in the Central Highlands.',N'Giới thiệu về người Ba Na',N'Introduction to the Ba Na people',N'Người Ba Na cư trú chủ yếu tại Gia Lai và Kon Tum, nơi nhà rông, sinh hoạt buôn làng và nghi lễ cộng đồng giữ vai trò trung tâm. Những yếu tố ấy tạo nên một không gian văn hóa đặc trưng của vùng cao nguyên.',N'The Ba Na live mainly in Gia Lai and Kon Tum, where communal rong houses, village life, and rituals play a central role.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Ba Na có lịch sử lâu đời ở Tây Nguyên, gắn với cộng đồng làng, lễ thức và nếp sống gần gũi với rừng núi.',N'The Ba Na have a long history in the Central Highlands, tied to village life, ritual, and the upland environment.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Nhà rông, cồng chiêng, điêu khắc gỗ và lễ hội cộng đồng là những nét đặc sắc của người Ba Na.',N'Rong houses, gong culture, wood carving, and communal festivals mark Ba Na identity.',N'Không gian sống',N'Living Space',N'Không gian sống của người Ba Na xoay quanh buôn làng, nhà rông và nếp sống cộng đồng trên cao nguyên.',N'Ba Na living space revolves around villages, communal houses, and highland community life.',N'Tây Nguyên',N'Central Highlands',N'Hơn 280 nghìn người',N'Over 280 thousand people',10),
        ('JRAI',N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',N'Không gian Tây Nguyên gắn với người Jrai',N'Central Highlands landscape associated with the Jrai people',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Chân dung người Jrai',N'Jrai portrait',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Jrai',N'Jrai community life',N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',N'Không gian sử thi và cồng chiêng Jrai',N'Jrai epic and gong culture scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng Jrai',N'Jrai communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian nhà ở của người Jrai',N'Jrai living space',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Jrai',N'Jrai card image',N'Dân tộc Jrai nổi bật với sử thi, nhà rông, cồng chiêng và đời sống cộng đồng ở Tây Nguyên.',N'The Jrai are known for epic traditions, rong houses, gong culture, and communal life in the Central Highlands.',N'Giới thiệu về người Jrai',N'Introduction to the Jrai people',N'Người Jrai sinh sống nhiều ở Gia Lai và các vùng phụ cận, với đời sống cộng đồng gắn bó cùng cồng chiêng, sử thi và nghi lễ buôn làng. Văn hóa Jrai góp phần tạo nên diện mạo giàu bản sắc của Tây Nguyên.',N'The Jrai live widely in Gia Lai and nearby areas, with community life shaped by gong culture, epics, and village rituals.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Jrai có lịch sử lâu đời tại Tây Nguyên, nơi văn hóa buôn làng và cảnh quan cao nguyên hòa quyện trong đời sống thường nhật.',N'The Jrai have a long history in the Central Highlands, where village culture and upland landscapes are deeply intertwined.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Cồng chiêng, sử thi, lễ bỏ mả và đời sống nhà rông là những dấu ấn quan trọng của người Jrai.',N'Gong culture, epics, funerary rituals, and communal houses are among the Jrai people’s defining cultural markers.',N'Không gian sống',N'Living Space',N'Không gian sống của người Jrai gắn với buôn làng, rẫy nương và nhịp sống cộng đồng của Tây Nguyên.',N'Jrai living space is rooted in villages, upland fields, and the communal rhythm of the Central Highlands.',N'Tây Nguyên',N'Central Highlands',N'Hơn 500 nghìn người',N'Over 500 thousand people',11),
        ('NUNG',N'https://images.unsplash.com/photo-1605518215584-5ea1ebda40c0?auto=format&fit=crop&w=1600&q=80',N'Không gian Đông Bắc gắn với người Nùng',N'Northeastern landscape associated with the Nung people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Nùng',N'Nung portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Nùng',N'Nung community life',N'https://images.unsplash.com/photo-1605518215584-5ea1ebda40c0?auto=format&fit=crop&w=1200&q=80',N'Không gian dân ca và lễ hội của người Nùng',N'Nung folk song and festival scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng Nùng',N'Nung communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Nùng',N'Nung living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Nùng',N'Nung card image',N'Dân tộc Nùng gắn với vùng Đông Bắc, nổi bật với dân ca, lễ hội và nghề thủ công truyền thống.',N'The Nung are rooted in the Northeast and known for folk songs, festivals, and craft traditions.',N'Giới thiệu về người Nùng',N'Introduction to the Nung people',N'Người Nùng cư trú nhiều tại Lạng Sơn, Cao Bằng và vùng Đông Bắc, nơi đời sống văn hóa gắn với dân ca, lễ hội và lao động nông nghiệp. Bản sắc của cộng đồng thể hiện qua tiếng nói, trang phục và tập quán cộng đồng.',N'The Nung live in Lang Son, Cao Bang, and the northeastern region, where cultural life is shaped by folk songs, festivals, and agriculture.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Nùng có lịch sử lâu đời ở vùng Đông Bắc, góp phần tạo nên sự phong phú văn hóa của khu vực biên cương phía Bắc.',N'The Nung have a long history in the Northeast and contribute to the cultural richness of northern border regions.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Dân ca, lễ hội, nghề rèn và đời sống bản làng là những yếu tố nổi bật của văn hóa Nùng.',N'Folk songs, festivals, smithing traditions, and village life stand out in Nung culture.',N'Không gian sống',N'Living Space',N'Không gian sống của người Nùng gắn với bản làng vùng đồi núi và những thung lũng canh tác nông nghiệp.',N'Nung living space is linked to hill villages and cultivated valleys.',N'Đông Bắc',N'Northeast',N'Hơn 1 triệu người',N'Over 1 million people',12),
        ('HANI',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',N'Không gian vùng biên gắn với người Hà Nhì',N'Borderland landscape associated with the Ha Nhi people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Hà Nhì',N'Ha Nhi portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Hà Nhì',N'Ha Nhi community life',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',N'Ruộng bậc thang và không gian sống của người Hà Nhì',N'Ha Nhi terraces and living space',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng Hà Nhì',N'Ha Nhi communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Hà Nhì',N'Ha Nhi living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Hà Nhì',N'Ha Nhi card image',N'Dân tộc Hà Nhì nổi bật với đời sống vùng biên, ruộng bậc thang và tín ngưỡng cộng đồng gắn với thiên nhiên.',N'The Ha Nhi are known for borderland life, terraces, and community beliefs tied to nature.',N'Giới thiệu về người Hà Nhì',N'Introduction to the Ha Nhi people',N'Người Hà Nhì sinh sống chủ yếu ở các khu vực biên giới Tây Bắc, nơi không gian sống gắn chặt với ruộng bậc thang, núi cao và cộng đồng bản làng khép kín. Những yếu tố ấy tạo nên sắc thái văn hóa riêng biệt của cộng đồng.',N'The Ha Nhi mainly live in northwestern border zones, where life is closely tied to terraces, mountains, and close-knit village communities.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Hà Nhì có lịch sử cư trú lâu đời ở vùng biên giới, thích nghi với cảnh quan núi cao và khí hậu khắc nghiệt.',N'The Ha Nhi have a long history in borderlands, adapting to mountain terrain and harsh climates.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Ruộng bậc thang, trang phục truyền thống và nghi lễ cộng đồng là những dấu ấn rõ nét của người Hà Nhì.',N'Terraces, traditional dress, and communal rituals are strong markers of Ha Nhi identity.',N'Không gian sống',N'Living Space',N'Không gian sống của người Hà Nhì gắn với núi cao, nương rẫy và các bản làng vùng biên.',N'Ha Nhi living space is rooted in mountains, upland fields, and border villages.',N'Vùng biên giới Tây Bắc',N'Northwestern borderlands',N'Hơn 25 nghìn người',N'Over 25 thousand people',13),
        ('COTU',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',N'Không gian Trường Sơn gắn với người Cơ Tu',N'Truong Son mountain landscape associated with the Co Tu people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Cơ Tu',N'Co Tu portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Cơ Tu',N'Co Tu community life',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',N'Không gian nhà Gươl của người Cơ Tu',N'Co Tu Guol house scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật điêu khắc và lễ hội của người Cơ Tu',N'Co Tu carving and festival arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Cơ Tu',N'Co Tu living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Cơ Tu',N'Co Tu card image',N'Dân tộc Cơ Tu gắn với miền núi Trường Sơn, nổi bật với nhà Gươl, điêu khắc gỗ và lễ hội cộng đồng.',N'The Co Tu are associated with the Truong Son mountains and known for Guol houses, wood carving, and community festivals.',N'Giới thiệu về người Cơ Tu',N'Introduction to the Co Tu people',N'Người Cơ Tu sinh sống ở miền núi Quảng Nam và Thừa Thiên Huế, nơi đời sống cộng đồng gắn với nhà Gươl, điêu khắc gỗ và lễ thức truyền thống. Không gian sinh hoạt của họ phản ánh sự gắn bó với rừng núi Trường Sơn.',N'The Co Tu live in the mountain areas of Quang Nam and Thua Thien Hue, where communal life centers on Guol houses, wood carving, and traditional rituals.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Cơ Tu có lịch sử lâu đời ở dãy Trường Sơn, nơi môi trường rừng núi định hình mạnh mẽ nếp sống và văn hóa cộng đồng.',N'The Co Tu have a long history in the Truong Son range, where forested mountains strongly shaped communal life and culture.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Nhà Gươl, điêu khắc gỗ, trang phục và lễ hội là những dấu ấn văn hóa nổi bật của người Cơ Tu.',N'Guol houses, wood carving, dress, and festivals are key markers of Co Tu culture.',N'Không gian sống',N'Living Space',N'Không gian sống của người Cơ Tu gắn với làng bản miền núi, nhà cộng đồng và sinh hoạt gắn bó với thiên nhiên.',N'Co Tu living space is rooted in mountain villages, communal houses, and close ties to nature.',N'Miền núi Trường Sơn',N'Truong Son highlands',N'Hơn 74 nghìn người',N'Over 74 thousand people',14),
        ('TAOI',N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',N'Không gian Trường Sơn gắn với người Tà Ôi',N'Truong Son mountain landscape associated with the Ta Oi people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Tà Ôi',N'Ta Oi portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Tà Ôi',N'Ta Oi community life',N'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',N'Không gian dệt zèng của người Tà Ôi',N'Ta Oi zeng weaving scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật và lễ hội của người Tà Ôi',N'Ta Oi ritual arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Tà Ôi',N'Ta Oi living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Tà Ôi',N'Ta Oi card image',N'Dân tộc Tà Ôi nổi bật với nghề dệt zèng, lễ hội và đời sống cộng đồng ở dãy Trường Sơn.',N'The Ta Oi are known for zeng weaving, festivals, and community life in the Truong Son range.',N'Giới thiệu về người Tà Ôi',N'Introduction to the Ta Oi people',N'Người Tà Ôi sinh sống tại vùng núi Trường Sơn, nổi bật với nghề dệt zèng, lễ hội cộng đồng và sinh hoạt gắn bó với bản làng. Không gian văn hóa của họ góp phần làm nên diện mạo đa dạng của miền núi Trung Bộ.',N'The Ta Oi live in the Truong Son mountains and are known for zeng weaving, communal festivals, and village life.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Tà Ôi có lịch sử cư trú lâu đời ở dãy Trường Sơn, nơi đời sống cộng đồng gắn chặt với núi rừng và nương rẫy.',N'The Ta Oi have a long history in the Truong Son range, where community life is closely tied to mountains and upland fields.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Nghề dệt zèng, lễ hội, trang phục và không gian cộng đồng là những yếu tố nổi bật của người Tà Ôi.',N'Zeng weaving, festivals, dress, and communal space are among the Ta Oi people’s defining cultural features.',N'Không gian sống',N'Living Space',N'Không gian sống của người Tà Ôi gắn với bản làng miền núi, nhà ở truyền thống và nếp sống cộng đồng vùng cao.',N'Ta Oi living space is rooted in mountain villages, traditional homes, and highland communal life.',N'Dãy Trường Sơn',N'Truong Son range',N'Hơn 50 nghìn người',N'Over 50 thousand people',15),
        ('CHURU',N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',N'Không gian chuyển tiếp giữa Tây Nguyên và duyên hải gắn với người Chu Ru',N'Transitional landscape between highlands and coast associated with the Chu Ru people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Chu Ru',N'Chu Ru portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Chu Ru',N'Chu Ru community life',N'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',N'Không gian nghề thủ công của người Chu Ru',N'Chu Ru craft scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng người Chu Ru',N'Chu Ru communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Chu Ru',N'Chu Ru living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Chu Ru',N'Chu Ru card image',N'Dân tộc Chu Ru mang nhiều nét văn hóa giao thoa giữa Tây Nguyên và duyên hải Nam Trung Bộ.',N'The Chu Ru reflect cultural interactions between the Central Highlands and the south-central coast.',N'Giới thiệu về người Chu Ru',N'Introduction to the Chu Ru people',N'Người Chu Ru sinh sống chủ yếu tại Lâm Đồng và Ninh Thuận, nơi không gian văn hóa phản ánh rõ sự giao thoa giữa cao nguyên và duyên hải. Sinh hoạt cộng đồng, thủ công và lễ tục là những dấu ấn đặc sắc của cộng đồng này.',N'The Chu Ru live mainly in Lam Dong and Ninh Thuan, where their culture reflects interactions between upland and coastal regions.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Chu Ru có lịch sử cư trú lâu đời ở vùng chuyển tiếp giữa cao nguyên và duyên hải Nam Trung Bộ.',N'The Chu Ru have a long history in the transitional zone between the highlands and the south-central coast.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Nghề thủ công, lễ hội và đời sống cộng đồng là những nét nổi bật trong văn hóa Chu Ru.',N'Craft traditions, festivals, and communal life are important features of Chu Ru culture.',N'Không gian sống',N'Living Space',N'Không gian sống của người Chu Ru phản ánh mối liên hệ giữa nông nghiệp, thủ công và cộng đồng làng.',N'Chu Ru living space reflects ties between farming, craft, and village community.',N'Nam Trung Bộ và cao nguyên lân cận',N'South-central coast and nearby highlands',N'Hơn 23 nghìn người',N'Over 23 thousand people',16),
        ('SANDIU',N'https://images.unsplash.com/photo-1605518215584-5ea1ebda40c0?auto=format&fit=crop&w=1600&q=80',N'Không gian trung du gắn với người Sán Dìu',N'Midland landscape associated with the San Diu people',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Chân dung người Sán Dìu',N'San Diu portrait',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Sinh hoạt cộng đồng người Sán Dìu',N'San Diu community life',N'https://images.unsplash.com/photo-1605518215584-5ea1ebda40c0?auto=format&fit=crop&w=1200&q=80',N'Không gian dân ca Soọng cô',N'Soong Co singing scene',N'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',N'Nghệ thuật cộng đồng người Sán Dìu',N'San Diu communal arts',N'https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80',N'Không gian cư trú của người Sán Dìu',N'San Diu living space',N'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',N'Ảnh đại diện dân tộc Sán Dìu',N'San Diu card image',N'Dân tộc Sán Dìu nổi bật với dân ca Soọng cô, lễ tục cộng đồng và đời sống trung du Bắc Bộ.',N'The San Diu are known for Soong Co singing, communal rituals, and life in the northern midlands.',N'Giới thiệu về người Sán Dìu',N'Introduction to the San Diu people',N'Người Sán Dìu sinh sống tại vùng trung du Bắc Bộ, nơi dân ca Soọng cô, sinh hoạt cộng đồng và lao động nông nghiệp tạo nên diện mạo văn hóa riêng. Không gian sống của họ phản ánh rõ mối quan hệ giữa cộng đồng và cảnh quan trung du.',N'The San Diu live in the northern midlands, where Soong Co singing, communal life, and agriculture shape their cultural identity.',N'Lịch sử & nguồn gốc',N'History & Origins',N'Người Sán Dìu có lịch sử cư trú lâu dài ở vùng trung du Bắc Bộ, góp phần làm phong phú đời sống văn hóa của khu vực này.',N'The San Diu have a long history in the northern midlands and add to the cultural richness of the region.',N'Đặc trưng văn hóa',N'Cultural Identity',N'Dân ca Soọng cô, lễ tục cộng đồng và đời sống nông nghiệp là những đặc điểm tiêu biểu của người Sán Dìu.',N'Soong Co singing, communal rituals, and agricultural life are among the San Diu’s defining traits.',N'Không gian sống',N'Living Space',N'Không gian sống của người Sán Dìu gắn với đồi núi thấp, ruộng vườn và các cộng đồng làng bản trung du.',N'San Diu living space is linked to low hills, fields, and midland village communities.',N'Trung du Bắc Bộ',N'Northern midlands',N'Hơn 180 nghìn người',N'Over 180 thousand people',17)
    ) AS v(MaDanToc,
        HeroBackgroundImageUrl, HeroBackgroundAltVI, HeroBackgroundAltEN,
        HeroForegroundImageUrl, HeroForegroundAltVI, HeroForegroundAltEN,
        IntroImageUrl, IntroImageAltVI, IntroImageAltEN,
        FeatureHighlightImageUrl, FeatureHighlightAltVI, FeatureHighlightAltEN,
        MusicImageUrl, MusicImageAltVI, MusicImageAltEN,
        ArchitectureImageUrl, ArchitectureImageAltVI, ArchitectureImageAltEN,
        CardImageUrl, CardImageAltVI, CardImageAltEN,
        HeroSubtitleVI, HeroSubtitleEN,
        OverviewTitleVI, OverviewTitleEN, OverviewBodyVI, OverviewBodyEN,
        HistoryTitleVI, HistoryTitleEN, HistoryBodyVI, HistoryBodyEN,
        CultureTitleVI, CultureTitleEN, CultureBodyVI, CultureBodyEN,
        ArchitectureTitleVI, ArchitectureTitleEN, ArchitectureBodyVI, ArchitectureBodyEN,
        PrimaryRegionLabelVI, PrimaryRegionLabelEN, PopulationLabelVI, PopulationLabelEN, DisplayOrder)
      ON v.MaDanToc = dt.MaDanToc