/* =========================================================
   BATCH 1 - SEED TỈNH THÀNH ĐỘNG THỰC TẾ
   Bổ sung thêm các tỉnh đại diện nhiều vùng, theo pattern idempotent
   ========================================================= */

SET NOCOUNT ON;

INSERT INTO dbo.TinhThanh (
    MaTinh, TenVI, TenEN, LoaiTinhVI, LoaiTinhEN, VungID,
    TieuVungVI, TieuVungEN, DienTichKm2, DanSo,
    AreaDisplayVI, AreaDisplayEN, PopulationDisplayVI, PopulationDisplayEN,
    TagsJsonVI, TagsJsonEN, TagsTextVI, TagsTextEN,
    AnhDaiDienUrl, AnhDaiDienAltVI, AnhDaiDienAltEN,
    TieuDePhuVI, TieuDePhuEN, TongQuanVI, TongQuanEN,
    ThoiTietMacDinhVI, ThoiTietMacDinhEN, ThoiDiemDepVI, ThoiDiemDepEN,
    ThongTinThanhLapVI, ThongTinThanhLapEN, ThongTinHanhChinhVI, ThongTinHanhChinhEN,
    MuiGio, MaVungDienThoai,
    HeroImageUrl, HeroImageAltVI, HeroImageAltEN,
    SidebarImageUrl, SidebarImageAltVI, SidebarImageAltEN,
    DiaDiemJsonVI, DiaDiemJsonEN,
    VanHoaJsonVI, VanHoaJsonEN,
    AmThucJsonVI, AmThucJsonEN,
    LichTrinhJsonVI, LichTrinhJsonEN,
    HoatDong, ThuTuHienThi
)
SELECT
    'da-nang', N'Đà Nẵng', N'Da Nang', N'Thành phố trực thuộc TW', N'Municipality', vv.VungID,
    N'Nam Trung Bộ', N'South Central Coast', 1285.00, 1160000,
    N'1,285 km²', N'1,285 km²', N'1.16 triệu người', N'1.16 million people',
    N'["Biển Mỹ Khê","Cầu Rồng","Bà Nà Hills"]', N'["My Khe Beach","Dragon Bridge","Ba Na Hills"]',
    N'Biển Mỹ Khê, Cầu Rồng, Bà Nà Hills', N'My Khe Beach, Dragon Bridge, Ba Na Hills',
    N'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    N'Toàn cảnh bờ biển Đà Nẵng',
    N'Da Nang coastline panorama',
    N'Thành phố biển năng động của miền Trung',
    N'The vibrant coastal city of Central Vietnam',
    N'Đà Nẵng là đô thị hiện đại của miền Trung, nổi tiếng với bãi biển đẹp, hạ tầng du lịch phát triển và vai trò kết nối giữa Huế - Hội An. Thành phố kết hợp hài hòa giữa không gian biển, sông và núi.',
    N'Da Nang is a modern city in Central Vietnam, known for beautiful beaches, strong tourism infrastructure, and its role as a bridge between Hue and Hoi An. It blends coast, river, and mountains into one destination.',
    N'29°C - Nắng đẹp', N'29°C - Sunny',
    N'Tháng 2 - Tháng 8', N'February - August',
    N'1997 (trực thuộc TW)', N'1997 (municipality status)',
    N'6 quận, 2 huyện', N'6 urban districts, 2 rural districts',
    N'UTC+7', N'236',
    N'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    N'Biển Đà Nẵng nhìn từ trên cao',
    N'Aerial view of Da Nang beach',
    N'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=900&q=80',
    N'Cầu Rồng và sông Hàn về đêm',
    N'Dragon Bridge and Han River at night',
    N'[{"title":"Biển Mỹ Khê","desc":"Một trong những bãi biển nổi tiếng nhất Việt Nam với bờ cát dài và nước trong xanh."},{"title":"Cầu Rồng","desc":"Biểu tượng hiện đại của thành phố, nổi bật với màn phun lửa và nước cuối tuần."},{"title":"Bà Nà Hills","desc":"Khu du lịch nổi tiếng với khí hậu mát mẻ, cáp treo và Cầu Vàng."}]',
    N'[{"title":"My Khe Beach","desc":"One of Vietnam''s most famous beaches, known for its long sandy shoreline and clear water."},{"title":"Dragon Bridge","desc":"A modern city icon, especially well known for its weekend fire and water show."},{"title":"Ba Na Hills","desc":"A mountain resort known for its cool climate, cable car, and the Golden Bridge."}]',
    N'["🌊 Biển Mỹ Khê","🌉 Cầu Rồng","🎆 Lễ hội pháo hoa","⛰ Núi Sơn Trà"]',
    N'["🌊 My Khe Beach","🌉 Dragon Bridge","🎆 Fireworks Festival","⛰ Son Tra Peninsula"]',
    N'[{"title":"Mì Quảng Đà Nẵng","imageUrl":"https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=80"},{"title":"Bánh tráng cuốn thịt heo","imageUrl":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80"},{"title":"Hải sản ven biển","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"title":"Da Nang Mi Quang","imageUrl":"https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=80"},{"title":"Pork rice paper rolls","imageUrl":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80"},{"title":"Coastal seafood","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"time":"07:30","task":"Đón bình minh tại biển Mỹ Khê và thưởng thức bữa sáng với mì Quảng."},{"time":"10:00","task":"Tham quan bán đảo Sơn Trà và ngắm toàn cảnh thành phố từ trên cao."},{"time":"15:00","task":"Khám phá Bà Nà Hills hoặc khu vực trung tâm ven sông Hàn."},{"time":"20:00","task":"Dạo cầu Rồng và thưởng thức hải sản tươi sống ven biển."}]',
    N'[{"time":"07:30","task":"Catch the sunrise at My Khe Beach and enjoy Mi Quang for breakfast."},{"time":"10:00","task":"Visit Son Tra Peninsula for panoramic city views."},{"time":"15:00","task":"Explore Ba Na Hills or the central Han River district."},{"time":"20:00","task":"Walk around Dragon Bridge and enjoy fresh coastal seafood."}]',
    1, 4
FROM dbo.VungVanHoa vv
WHERE vv.MaVung = 'TRUNG_BO'
  AND NOT EXISTS (SELECT 1 FROM dbo.TinhThanh WHERE MaTinh = 'da-nang');

INSERT INTO dbo.TinhThanh (
    MaTinh, TenVI, TenEN, LoaiTinhVI, LoaiTinhEN, VungID,
    TieuVungVI, TieuVungEN, DienTichKm2, DanSo,
    AreaDisplayVI, AreaDisplayEN, PopulationDisplayVI, PopulationDisplayEN,
    TagsJsonVI, TagsJsonEN, TagsTextVI, TagsTextEN,
    AnhDaiDienUrl, AnhDaiDienAltVI, AnhDaiDienAltEN,
    TieuDePhuVI, TieuDePhuEN, TongQuanVI, TongQuanEN,
    ThoiTietMacDinhVI, ThoiTietMacDinhEN, ThoiDiemDepVI, ThoiDiemDepEN,
    ThongTinThanhLapVI, ThongTinThanhLapEN, ThongTinHanhChinhVI, ThongTinHanhChinhEN,
    MuiGio, MaVungDienThoai,
    HeroImageUrl, HeroImageAltVI, HeroImageAltEN,
    SidebarImageUrl, SidebarImageAltVI, SidebarImageAltEN,
    DiaDiemJsonVI, DiaDiemJsonEN,
    VanHoaJsonVI, VanHoaJsonEN,
    AmThucJsonVI, AmThucJsonEN,
    LichTrinhJsonVI, LichTrinhJsonEN,
    HoatDong, ThuTuHienThi
)
SELECT
    'quang-ninh', N'Quảng Ninh', N'Quang Ninh', N'Tỉnh', N'Province', vv.VungID,
    N'Đông Bắc', N'Northeast', 6178.00, 1340000,
    N'6,178 km²', N'6,178 km²', N'1.34 triệu người', N'1.34 million people',
    N'["Vịnh Hạ Long","Yên Tử","Biển đảo"]', N'["Ha Long Bay","Yen Tu","Sea and islands"]',
    N'Vịnh Hạ Long, Yên Tử, Biển đảo', N'Ha Long Bay, Yen Tu, Sea and islands',
    N'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
    N'Phong cảnh vịnh Hạ Long',
    N'Ha Long Bay landscape',
    N'Di sản biển đảo nổi bật của miền Bắc',
    N'A major northern destination of heritage, coast, and islands',
    N'Quảng Ninh nổi tiếng với vịnh Hạ Long - di sản thiên nhiên thế giới, cùng hệ thống đảo, bãi biển và không gian tâm linh Yên Tử. Tỉnh giữ vai trò quan trọng trong du lịch biển đảo và công nghiệp phía Bắc.',
    N'Quang Ninh is best known for Ha Long Bay, a world natural heritage site, alongside its islands, beaches, and the spiritual space of Yen Tu. It is one of northern Vietnam''s most important tourism and industrial provinces.',
    N'27°C - Có nắng', N'27°C - Sunny intervals',
    N'Tháng 10 - Tháng 4', N'October - April',
    N'1963 (thành lập tỉnh)', N'1963 (province established)',
    N'4 thành phố, 2 thị xã, 7 huyện', N'4 cities, 2 towns, 7 districts',
    N'UTC+7', N'203',
    N'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1400&q=80',
    N'Vịnh Hạ Long nhìn từ trên cao',
    N'Aerial view of Ha Long Bay',
    N'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80',
    N'Biển xanh và núi đá Quảng Ninh',
    N'Blue sea and limestone islands in Quang Ninh',
    N'[{"title":"Vịnh Hạ Long","desc":"Di sản thiên nhiên thế giới với hàng nghìn đảo đá vôi và làn nước xanh đặc trưng."},{"title":"Yên Tử","desc":"Quần thể danh thắng và trung tâm Phật giáo gắn với thiền phái Trúc Lâm."},{"title":"Bãi Cháy","desc":"Khu vực biển và giải trí nổi tiếng, thuận tiện cho nghỉ dưỡng gia đình."}]',
    N'[{"title":"Ha Long Bay","desc":"A world natural heritage site with thousands of limestone islets and emerald waters."},{"title":"Yen Tu","desc":"A scenic and spiritual complex linked to Truc Lam Zen Buddhism."},{"title":"Bai Chay","desc":"A well-known coastal leisure area ideal for family trips and resort stays."}]',
    N'["⛵ Du thuyền vịnh","⛰ Núi đá vôi","🛕 Yên Tử","🌊 Biển đảo Đông Bắc"]',
    N'["⛵ Bay cruises","⛰ Limestone karsts","🛕 Yen Tu","🌊 Northeastern coast and islands"]',
    N'[{"title":"Chả mực Hạ Long","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"},{"title":"Sam biển Quảng Yên","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"},{"title":"Hàu nướng mỡ hành","imageUrl":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"title":"Ha Long squid cakes","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"},{"title":"Quang Yen horseshoe crab","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"},{"title":"Grilled oysters with scallion oil","imageUrl":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"time":"08:00","task":"Khởi hành tham quan vịnh Hạ Long bằng du thuyền buổi sáng."},{"time":"11:30","task":"Thưởng thức chả mực và hải sản địa phương tại Hạ Long."},{"time":"15:00","task":"Di chuyển tới Yên Tử hoặc bảo tàng Quảng Ninh tùy hành trình."},{"time":"19:00","task":"Dạo biển Bãi Cháy và nghỉ đêm tại khu vực ven vịnh."}]',
    N'[{"time":"08:00","task":"Start the morning with a cruise across Ha Long Bay."},{"time":"11:30","task":"Enjoy squid cakes and local seafood in Ha Long."},{"time":"15:00","task":"Visit Yen Tu or the Quang Ninh Museum depending on your route."},{"time":"19:00","task":"Walk along Bai Chay beach and stay overnight near the bay."}]',
    1, 5
FROM dbo.VungVanHoa vv
WHERE vv.MaVung = 'BAC_BO'
  AND NOT EXISTS (SELECT 1 FROM dbo.TinhThanh WHERE MaTinh = 'quang-ninh');

INSERT INTO dbo.TinhThanh (
    MaTinh, TenVI, TenEN, LoaiTinhVI, LoaiTinhEN, VungID,
    TieuVungVI, TieuVungEN, DienTichKm2, DanSo,
    AreaDisplayVI, AreaDisplayEN, PopulationDisplayVI, PopulationDisplayEN,
    TagsJsonVI, TagsJsonEN, TagsTextVI, TagsTextEN,
    AnhDaiDienUrl, AnhDaiDienAltVI, AnhDaiDienAltEN,
    TieuDePhuVI, TieuDePhuEN, TongQuanVI, TongQuanEN,
    ThoiTietMacDinhVI, ThoiTietMacDinhEN, ThoiDiemDepVI, ThoiDiemDepEN,
    ThongTinThanhLapVI, ThongTinThanhLapEN, ThongTinHanhChinhVI, ThongTinHanhChinhEN,
    MuiGio, MaVungDienThoai,
    HeroImageUrl, HeroImageAltVI, HeroImageAltEN,
    SidebarImageUrl, SidebarImageAltVI, SidebarImageAltEN,
    DiaDiemJsonVI, DiaDiemJsonEN,
    VanHoaJsonVI, VanHoaJsonEN,
    AmThucJsonVI, AmThucJsonEN,
    LichTrinhJsonVI, LichTrinhJsonEN,
    HoatDong, ThuTuHienThi
)
SELECT
    'da-lat', N'Đà Lạt', N'Da Lat', N'Thành phố trực thuộc tỉnh', N'Provincial city', vv.VungID,
    N'Tây Nguyên', N'Central Highlands', 394.00, 257000,
    N'394 km²', N'394 km²', N'257 nghìn người', N'257 thousand people',
    N'["Cao nguyên","Hoa","Kiến trúc Pháp"]', N'["Highland","Flowers","French architecture"]',
    N'Cao nguyên, Hoa, Kiến trúc Pháp', N'Highland, Flowers, French architecture',
    N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    N'Thung lũng và rừng thông Đà Lạt',
    N'Da Lat pine hills and valley',
    N'Thành phố ngàn hoa trên cao nguyên',
    N'The city of flowers in the highlands',
    N'Đà Lạt nổi tiếng với khí hậu mát mẻ quanh năm, rừng thông, hồ nước và không gian nghỉ dưỡng mang dấu ấn kiến trúc Pháp. Đây là điểm đến nổi bật của vùng Tây Nguyên và du lịch cao nguyên Việt Nam.',
    N'Da Lat is famous for its year-round cool weather, pine forests, lakes, and resort atmosphere shaped by French-era architecture. It is one of the most iconic destinations in Vietnam''s Central Highlands.',
    N'20°C - Se lạnh', N'20°C - Cool',
    N'Tháng 11 - Tháng 3', N'November - March',
    N'1893 (thời kỳ khám phá cao nguyên)', N'1893 (early colonial-era development)',
    N'Thuộc tỉnh Lâm Đồng, trung tâm du lịch cao nguyên', N'Part of Lam Dong Province, highland tourism center',
    N'UTC+7', N'263',
    N'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1400&q=80',
    N'Đồi thông và hồ nước tại Đà Lạt',
    N'Pine hills and lake scenery in Da Lat',
    N'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=80',
    N'Không gian trung tâm Đà Lạt về chiều',
    N'Da Lat town center in the afternoon',
    N'[{"title":"Hồ Xuân Hương","desc":"Không gian trung tâm đặc trưng của Đà Lạt, phù hợp dạo bộ và ngắm cảnh."},{"title":"Thung lũng Tình Yêu","desc":"Điểm đến lãng mạn nổi tiếng với cảnh quan đồi thông và hồ nước."},{"title":"Đồi chè Cầu Đất","desc":"Không gian cao nguyên xanh mát, thích hợp trải nghiệm bình minh và săn mây."}]',
    N'[{"title":"Xuan Huong Lake","desc":"A central scenic space in Da Lat, ideal for walking and sightseeing."},{"title":"Valley of Love","desc":"A romantic destination known for pine hills and lakes."},{"title":"Cau Dat Tea Hill","desc":"A cool green highland space perfect for sunrise and cloud hunting."}]',
    N'["🌲 Rừng thông","🌸 Lễ hội hoa","☕ Cà phê cao nguyên","🏡 Biệt thự Pháp"]',
    N'["🌲 Pine forests","🌸 Flower festival","☕ Highland coffee","🏡 French villas"]',
    N'[{"title":"Bánh căn Đà Lạt","imageUrl":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80"},{"title":"Lẩu gà lá é","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"},{"title":"Dâu tây và nông sản cao nguyên","imageUrl":"https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"title":"Da Lat mini pancakes","imageUrl":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80"},{"title":"Chicken hotpot with lemon basil","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"},{"title":"Strawberries and highland produce","imageUrl":"https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"time":"07:00","task":"Thưởng thức cà phê và ngắm bình minh tại đồi chè Cầu Đất."},{"time":"10:00","task":"Dạo quanh hồ Xuân Hương và các điểm trung tâm thành phố."},{"time":"15:00","task":"Tham quan vườn hoa hoặc khu vực ngoại ô với đồi thông, nông trại."},{"time":"19:00","task":"Khám phá ẩm thực đêm Đà Lạt và không khí se lạnh cao nguyên."}]',
    N'[{"time":"07:00","task":"Enjoy coffee and sunrise at Cau Dat Tea Hill."},{"time":"10:00","task":"Walk around Xuan Huong Lake and the city center."},{"time":"15:00","task":"Visit flower gardens or nearby countryside with pine forests and farms."},{"time":"19:00","task":"Explore Da Lat''s night food scene and cool highland air."}]',
    1, 6
FROM dbo.VungVanHoa vv
WHERE vv.MaVung = 'TAY_NGUYEN'
  AND NOT EXISTS (SELECT 1 FROM dbo.TinhThanh WHERE MaTinh = 'da-lat');

INSERT INTO dbo.TinhThanh (
    MaTinh, TenVI, TenEN, LoaiTinhVI, LoaiTinhEN, VungID,
    TieuVungVI, TieuVungEN, DienTichKm2, DanSo,
    AreaDisplayVI, AreaDisplayEN, PopulationDisplayVI, PopulationDisplayEN,
    TagsJsonVI, TagsJsonEN, TagsTextVI, TagsTextEN,
    AnhDaiDienUrl, AnhDaiDienAltVI, AnhDaiDienAltEN,
    TieuDePhuVI, TieuDePhuEN, TongQuanVI, TongQuanEN,
    ThoiTietMacDinhVI, ThoiTietMacDinhEN, ThoiDiemDepVI, ThoiDiemDepEN,
    ThongTinThanhLapVI, ThongTinThanhLapEN, ThongTinHanhChinhVI, ThongTinHanhChinhEN,
    MuiGio, MaVungDienThoai,
    HeroImageUrl, HeroImageAltVI, HeroImageAltEN,
    SidebarImageUrl, SidebarImageAltVI, SidebarImageAltEN,
    DiaDiemJsonVI, DiaDiemJsonEN,
    VanHoaJsonVI, VanHoaJsonEN,
    AmThucJsonVI, AmThucJsonEN,
    LichTrinhJsonVI, LichTrinhJsonEN,
    HoatDong, ThuTuHienThi
)
SELECT
    'phu-quoc', N'Phú Quốc', N'Phu Quoc', N'Thành phố đảo', N'Island city', vv.VungID,
    N'Đồng bằng sông Cửu Long', N'Mekong Delta', 589.00, 180000,
    N'589 km²', N'589 km²', N'180 nghìn người', N'180 thousand people',
    N'["Đảo ngọc","Biển xanh","Nghỉ dưỡng"]', N'["Pearl island","Blue sea","Resort travel"]',
    N'Đảo ngọc, Biển xanh, Nghỉ dưỡng', N'Pearl island, Blue sea, Resort travel',
    N'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    N'Bãi biển Phú Quốc nhìn từ trên cao',
    N'Aerial view of Phu Quoc beach',
    N'Đảo ngọc nhiệt đới của phương Nam',
    N'The tropical pearl island of southern Vietnam',
    N'Phú Quốc là điểm đến biển đảo nổi tiếng của Việt Nam với bãi biển dài, nước biển trong, rừng nguyên sinh và hệ sinh thái nghỉ dưỡng phát triển mạnh. Nơi đây kết hợp giữa thiên nhiên, du lịch và ẩm thực hải sản.',
    N'Phu Quoc is one of Vietnam''s most famous island destinations, known for long beaches, clear water, tropical forests, and a strong resort ecosystem. It brings together nature, travel, and coastal cuisine.',
    N'30°C - Nắng đẹp', N'30°C - Sunny',
    N'Tháng 11 - Tháng 4', N'November - April',
    N'2004 (huyện đảo), 2021 (thành phố)', N'2004 (island district), 2021 (city status)',
    N'Thuộc tỉnh Kiên Giang, thành phố đảo duy nhất của Việt Nam', N'Part of Kien Giang Province, the only island city in Vietnam',
    N'UTC+7', N'297',
    N'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    N'Bãi biển nhiệt đới tại Phú Quốc',
    N'Tropical beach in Phu Quoc',
    N'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=900&q=80',
    N'Hoàng hôn biển Phú Quốc',
    N'Phu Quoc sunset by the sea',
    N'[{"title":"Bãi Sao","desc":"Bãi biển nổi tiếng với cát trắng mịn và làn nước trong xanh đặc trưng."},{"title":"Chợ đêm Phú Quốc","desc":"Không gian ẩm thực và mua sắm sôi động vào buổi tối."},{"title":"Grand World - Bắc đảo","desc":"Khu du lịch giải trí hiện đại phù hợp nghỉ dưỡng và trải nghiệm gia đình."}]',
    N'[{"title":"Sao Beach","desc":"A famous beach known for fine white sand and crystal-clear water."},{"title":"Phu Quoc Night Market","desc":"A lively evening space for food and shopping."},{"title":"Grand World - North Island","desc":"A modern entertainment and resort zone for family-friendly travel."}]',
    N'["🏝 Biển đảo","🐟 Làng chài","🌅 Hoàng hôn","🛥 Du lịch nghỉ dưỡng"]',
    N'["🏝 Island beaches","🐟 Fishing villages","🌅 Sunsets","🛥 Resort travel"]',
    N'[{"title":"Gỏi cá trích","imageUrl":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=80"},{"title":"Nhum biển nướng","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"},{"title":"Hải sản chợ đêm","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"title":"Herring salad","imageUrl":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=80"},{"title":"Grilled sea urchin","imageUrl":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80"},{"title":"Night market seafood","imageUrl":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"}]',
    N'[{"time":"08:00","task":"Tắm biển và thư giãn tại Bãi Sao hoặc các bãi biển phía nam đảo."},{"time":"11:30","task":"Thưởng thức hải sản tươi sống và đặc sản địa phương."},{"time":"15:00","task":"Khám phá các điểm tham quan Bắc đảo hoặc làng chài truyền thống."},{"time":"18:30","task":"Ngắm hoàng hôn và dạo chợ đêm Phú Quốc."}]',
    N'[{"time":"08:00","task":"Relax at Sao Beach or other southern island beaches."},{"time":"11:30","task":"Enjoy fresh seafood and local island specialties."},{"time":"15:00","task":"Explore northern island attractions or traditional fishing villages."},{"time":"18:30","task":"Watch the sunset and stroll through the Phu Quoc night market."}]',
    1, 7
FROM dbo.VungVanHoa vv
WHERE vv.MaVung = 'DBSCL'
  AND NOT EXISTS (SELECT 1 FROM dbo.TinhThanh WHERE MaTinh = 'phu-quoc');
